begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  submission_id uuid not null default gen_random_uuid(),
  name text not null,
  email text not null,
  country_code text not null,
  phone text not null,
  phone_normalized text not null,
  activity text not null,
  advice text not null,
  question text,
  status text not null default 'new',
  platform text not null default 'landing',
  source_detail text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  gclid text,
  fbclid text,
  registered_at timestamptz,
  scheduled_at timestamptz,
  calendar_event_id text,
  odoo_lead_id bigint,
  odoo_sync_status text not null default 'pending',
  odoo_sync_error text,
  odoo_synced_at timestamptz,
  source_version bigint not null default 1,
  odoo_synced_version bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint leads_submission_id_key unique (submission_id),
  constraint leads_name_check check (
    name = btrim(name) and char_length(name) between 2 and 120
  ),
  constraint leads_email_check check (
    email = btrim(email)
    and char_length(email) between 3 and 254
    and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  constraint leads_country_code_check check (
    country_code ~ '^\+[1-9][0-9]{0,2}$'
  ),
  constraint leads_phone_check check (
    phone = btrim(phone) and char_length(phone) between 7 and 32
  ),
  constraint leads_phone_normalized_check check (
    phone_normalized ~ '^\+[1-9][0-9]{7,14}$'
  ),
  constraint leads_activity_check check (
    activity = btrim(activity) and char_length(activity) between 1 and 160
  ),
  constraint leads_advice_check check (
    advice = btrim(advice) and char_length(advice) between 1 and 160
  ),
  constraint leads_question_check check (
    question is null or char_length(question) <= 2000
  ),
  constraint leads_status_check check (
    status in ('new', 'contacted', 'qualified', 'scheduled', 'won', 'lost', 'spam')
  ),
  constraint leads_platform_check check (
    platform ~ '^[a-z0-9][a-z0-9_-]{0,79}$'
  ),
  constraint leads_source_detail_check check (
    source_detail is null or char_length(source_detail) <= 160
  ),
  constraint leads_utm_source_check check (
    utm_source is null or char_length(utm_source) <= 100
  ),
  constraint leads_utm_medium_check check (
    utm_medium is null or char_length(utm_medium) <= 100
  ),
  constraint leads_utm_campaign_check check (
    utm_campaign is null or char_length(utm_campaign) <= 200
  ),
  constraint leads_utm_content_check check (
    utm_content is null or char_length(utm_content) <= 200
  ),
  constraint leads_utm_term_check check (
    utm_term is null or char_length(utm_term) <= 200
  ),
  constraint leads_gclid_check check (
    gclid is null or char_length(gclid) <= 512
  ),
  constraint leads_fbclid_check check (
    fbclid is null or char_length(fbclid) <= 512
  ),
  constraint leads_calendar_event_id_check check (
    calendar_event_id is null or char_length(calendar_event_id) <= 255
  ),
  constraint leads_odoo_lead_id_check check (
    odoo_lead_id is null or odoo_lead_id > 0
  ),
  constraint leads_odoo_sync_status_check check (
    odoo_sync_status in ('pending', 'synced', 'failed', 'skipped')
  ),
  constraint leads_odoo_sync_error_check check (
    odoo_sync_error is null or char_length(odoo_sync_error) <= 4000
  ),
  constraint leads_source_version_check check (source_version > 0),
  constraint leads_synced_version_check check (
    odoo_synced_version is null
    or (odoo_synced_version > 0 and odoo_synced_version <= source_version)
  )
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_email_idx on public.leads (email);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_platform_idx on public.leads (platform);
create index if not exists leads_utm_campaign_idx on public.leads (utm_campaign);
create index if not exists leads_odoo_sync_status_idx on public.leads (odoo_sync_status);
create index if not exists leads_sync_queue_idx
  on public.leads (odoo_sync_status, source_version, created_at);
create index if not exists leads_unsynced_idx
  on public.leads (created_at)
  where odoo_synced_version is distinct from source_version;
create unique index if not exists leads_odoo_lead_id_key
  on public.leads (odoo_lead_id)
  where odoo_lead_id is not null;

create or replace function public.leads_set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  new.source_version = old.source_version;

  if row(
    new.name, new.email, new.country_code, new.phone, new.phone_normalized,
    new.activity, new.advice, new.question, new.status, new.platform,
    new.source_detail, new.utm_source, new.utm_medium, new.utm_campaign,
    new.utm_content, new.utm_term, new.gclid, new.fbclid, new.registered_at,
    new.scheduled_at, new.calendar_event_id
  ) is distinct from row(
    old.name, old.email, old.country_code, old.phone, old.phone_normalized,
    old.activity, old.advice, old.question, old.status, old.platform,
    old.source_detail, old.utm_source, old.utm_medium, old.utm_campaign,
    old.utm_content, old.utm_term, old.gclid, old.fbclid, old.registered_at,
    old.scheduled_at, old.calendar_event_id
  ) then
    new.source_version = old.source_version + 1;
    new.odoo_sync_status = 'pending';
    new.odoo_sync_error = null;
  end if;

  return new;
end;
$$;

revoke all on function public.leads_set_updated_at() from public;

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at
before update on public.leads
for each row execute function public.leads_set_updated_at();

alter table public.leads enable row level security;
revoke all on table public.leads from anon, authenticated;
revoke all on sequence public.leads_id_seq from anon, authenticated;
grant select, insert, update on table public.leads to service_role;
grant usage, select on sequence public.leads_id_seq to service_role;

comment on table public.leads is
  'Primary system of record for marketing leads; Odoo is a downstream consumer.';

commit;
