begin;

create table if not exists public.meetings (
  id bigint generated by default as identity primary key,

  lead_id bigint not null
    references public.leads(id)
    on delete restrict,

  provider text not null default 'zcal',
  provider_event_id text not null,
  status text not null default 'scheduled',
  scheduled_at timestamptz not null,
  timezone text not null default 'UTC',
  meeting_url text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint meetings_provider_check
    check (provider in ('zcal')),

  constraint meetings_provider_event_id_check
    check (char_length(btrim(provider_event_id)) between 1 and 255),

  constraint meetings_status_check
    check (status in (
      'scheduled',
      'cancelled',
      'completed',
      'no_show'
    )),

  constraint meetings_timezone_check
    check (char_length(btrim(timezone)) between 1 and 80),

  constraint meetings_url_check
    check (
      meeting_url is null
      or char_length(btrim(meeting_url)) between 1 and 2048
    )
);

create unique index if not exists meetings_provider_event_key
  on public.meetings(provider, provider_event_id);

create index if not exists meetings_lead_id_idx
  on public.meetings(lead_id);

create index if not exists meetings_scheduled_at_idx
  on public.meetings(scheduled_at);

create index if not exists meetings_status_idx
  on public.meetings(status);

create or replace function public.set_meeting_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_meeting_updated_at() from public;

drop trigger if exists meetings_set_updated_at on public.meetings;
create trigger meetings_set_updated_at
before update on public.meetings
for each row
execute function public.set_meeting_updated_at();

alter table public.meetings enable row level security;

revoke all on table public.meetings from anon, authenticated;
revoke all on sequence public.meetings_id_seq from anon, authenticated;
grant select, insert, update on table public.meetings to service_role;
grant usage, select on sequence public.meetings_id_seq to service_role;

comment on table public.meetings is
  'Calendar meetings confirmed by external scheduling providers.';

comment on column public.meetings.lead_id is
  'Lead associated with the scheduled meeting.';

comment on column public.meetings.provider_event_id is
  'Provider event identifier used for webhook idempotency.';

commit;
